services:
  footballsquaregameservices:
    image: footballsquaregameservices
    build:
      context: FootballSquareGameServices
      dockerfile: Dockerfile
    ports:
      - '3101:8080'

  squaremicroservices:
    image: squaremicroservices
    build:
      context: Microservices/SquareMicroservices
      dockerfile: Dockerfile
    ports:
      - '${PORT:-3000}:3000'

  footballsquaregamemicroservices:
    image: footballsquaregamemicroservices
    build:
      context: Microservices/FootballSquareGameMicroservices
      dockerfile: Dockerfile
    ports:
      - '${PORT:-3001}:3001'

  gamemicroservices:
    image: gamemicroservices
    build:
      context: Microservices/GameMicroservices
      dockerfile: Dockerfile
    ports:
      - '${PORT:-3002}:3002'

  usermicroservices:
    image: usermicroservices
    build:
      context: Microservices/UserMicroservices
      dockerfile: Dockerfile
    ports:
      - '${PORT:-3003}:3003'

  db:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
    ports:
      - "6379:6379"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example

volumes:
  db-data: